[[actions]]
name = "play"
platform = "windows"
path = "PotatoesExtrasLg/PotatoesExtrasLg.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "PotatoesExtrasLg/PotatoesExtrasLg"
args = ["--launched-through-itch"]
