[[actions]]
name = "play"
platform = "windows"
path = "PotatoesExtrasCg/PotatoesExtrasCg.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "PotatoesExtrasCg/PotatoesExtrasCg"
args = ["--launched-through-itch"]
